name: 'ioBroker Testing: Adapter tests'
author: 'AlCalzone'
#description: 'Greet someone'

inputs:
  node-version:
    description: 'Node.js version'
    required: true
  os:
    description: 'The operation system to use'
    required: true
  build:
    description: 'Set to true when the adapter needs a build step before testing'
    default: 'false'
  build-command: 
    description: 'Overwrite the default build command'
    default: 'npm run build'

# Conditional syntax isn't supported, but there are workarounds:
# https://github.com/actions/runner/issues/834#issuecomment-909921245

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      shell: bash
      run: npm ci

    - name: Create a clean build
      shell: bash
      run: |
        if ${{ inputs.build }}; then
          ${{ inputs.build-command }}
        else
          echo "Skipping build step..."
        fi

    - name: Run unit tests
      shell: bash
      run: npm run test:unit

    - name: Run integration tests
      shell: bash
      run: npm run test:integration
      env:
        DEBUG: 'testing:*'
